# Generated by Django 4.0.4 on 2022-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeJbStats',
            fields=[
                ('cafe_id', models.SmallIntegerField(blank=True, null=True)),
                ('cafe_name', models.CharField(blank=True, max_length=63, null=True)),
                ('location_category', models.CharField(blank=True, max_length=15, null=True)),
                ('location_detail', models.CharField(blank=True, max_length=63, null=True)),
                ('home_url', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(blank=True, max_length=63, null=True)),
                ('genre', models.CharField(blank=True, max_length=63, null=True)),
                ('activity', models.CharField(blank=True, max_length=15, null=True)),
                ('recom_user', models.CharField(blank=True, max_length=15, null=True)),
                ('review_n', models.BigIntegerField()),
                ('star_stat', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('medal_stat', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('diff_stat', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('success_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('left_stat', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('limit_time', models.SmallIntegerField(blank=True, null=True)),
                ('hint_stst', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('trs_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'escape_jb_stats',
                'managed': False,
            },
        ),
    ]
